# Generated by Django 5.1.4 on 2024-12-20 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flights", "0001_initial"),
        ("flyhub_manager", "0002_remove_ticket_flight_remove_order_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flight",
            name="crew",
            field=models.ManyToManyField(
                related_name="flights", to="flyhub_manager.crew"
            ),
        ),
    ]
