# Generated by Django 5.1.4 on 2024-12-19 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("flyhub_manager", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ticket",
            name="flight",
        ),
        migrations.RemoveField(
            model_name="order",
            name="user",
        ),
        migrations.RemoveField(
            model_name="ticket",
            name="order",
        ),
        migrations.RemoveField(
            model_name="route",
            name="destination",
        ),
        migrations.RemoveField(
            model_name="route",
            name="source",
        ),
        migrations.DeleteModel(
            name="Flight",
        ),
        migrations.DeleteModel(
            name="Order",
        ),
        migrations.DeleteModel(
            name="Ticket",
        ),
        migrations.DeleteModel(
            name="Route",
        ),
    ]
